# .readthedocs.yaml
# Read the Docs configuration file for MkDocs

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: requirements.txt

mkdocs:
  configuration: mkdocs.yml
