site_name: Hoobs Live
nav:
    - Home: index.md
    - Server:
      - Connecting: server/connecting.md
      - Places: server/places.md
    - Lore:
      - Hoobasaurus: lore/hoobasaurus.md
      - Hooba's Mom: lore/hoobasmom.md
      - Hooba's Dad: lore/hoobasdad.md
      - Hoobibo: lore/hoobibo.md

    - Rules: rules/index.md
    - Discord: discord/index.md
    - Privacy: privacy.md
site_description: Hoobs Live Field Manual
theme:
  name: material
  font: false
  logo: img/logo.png
  favicon: img/favicon.ico
  custom_dir: overrides
  palette:
    scheme: slate
    primary: custom
    accent: red
  features:
    - header.autohide
extra_css:
  - stylesheets/extra.css