site_name: Hoobs Live
nav:
    - Home: index.md
    - YouTube: youtube/index.md
    - Discord: discord/index.md
    - Rules: rules/index.md 
    - Help: help/connecting.md
site_description: Hoobs Live Field Manual
theme:
  features:
    - header.autohide
  name: material
  logo: img/logo.png
  palette:
    scheme: default
    primary: red
    accent: red
extra:
  analytics:
    provider: google
    property: UA-111512157-3
