site_name: Hoobs Live
nav:
    - Home: index.md
    - Server: server/connecting.md
    - Lore: lore/index.md
    - Rules: rules/index.md
    - Discord: discord/index.md
    - Privacy: privacy.md
site_description: Hoobs Live Field Manual
theme:
  name: material
  font: false
  logo: img/logo.png
  favicon: img/favicon.ico
  custom_dir: overrides
  palette:
    scheme: slate
    primary: custom
    accent: red
  features:
    - header.autohide
extra_css:
  - /stylesheets/extra.css