site_name: Hoobs Live
nav:
    - Home: index.md
    - YouTube: youtube/index.md
    - Discord: discord/index.md
    - Rules: rules/index.md 
    - Help: help/connecting.md
site_description: Hoobs Live Field Manual
theme:
  name: material
  palette:
    primary: black
    accent: red
extra:
  analytics:
    provider: google
    property: UA-111512157-3
