site_name: Hoobs Live
nav:
    - Home: index.md
    - YouTube: youtube/index.md
    - Help: help/connecting.md
    - Rules: rules/index.md 
site_description: Hoobs Live Field Manual
theme:
  name: material
  palette:
    primary: red
    accent: red
